# MassGen Three Agent Configuration
# Gemini-2.5-flash, GPT-5-mini, and Claude-3.5-Haiku with builtin tools enabled

agents:
  - id: "gpt-5"
    backend:
      type: "openai"
      model: "gpt-5"
      text: 
        verbosity: "low"
      # reasoning:
      #   effort: "minimal"
      enable_web_search: true # reasoning and enable_web_search cannot be used synchronically
      # enable_code_execution: true
    # system_message: "You are a helpful AI assistant with web search and code execution capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

  - id: "gpt-5-mini"
    backend:
      type: "openai"
      model: "gpt-5-mini"
      text: 
        verbosity: "low"
      # reasoning:
      #   effort: "minimal"
      enable_web_search: true
      #enable_code_interpreter: true
    # system_message: "You are a helpful AI assistant with web search and code execution capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

  - id: "gpt-5-nano"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      text: 
        verbosity: "low"
      # reasoning:
      #   effort: "minimal"
      enable_web_search: true
      #enable_code_interpreter: true
    # system_message: "You are a helpful AI assistant with web search and code execution capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

ui:
  display_type: "rich_terminal"
  logging_enabled: true
