# MassGen Configuration
# Usage:
# uv run python -m massgen.cli --config massgen/configs/basic/single/single_gpt5nano_image_generation.yaml "Transform the uploaded image into a Studio Ghibli art style and save it directly into a file in your workspace."
agents:
  - id: "gpt5nano_agent1"
    backend:
      type: "openai"
      model: "gpt-5"
      # upload_files:
      #   - image_path: "/Users/danruiqi/Desktop/Danrui/Research/MassGen/git19/MassGen/massgen/configs/resources/v0.0.27-example/multimodality.jpg" # Example image to be used by the agent
      cwd: "workspace1"  # Working directory for file operations
      enable_image_generation: true
    system_message: |
      You are an expert in image generation and transformation.
      Please call the image generation tool to create or modify images based on user requests.

orchestrator:
    snapshot_storage: "snapshots"  # Directory to store workspace snapshots
    agent_temporary_workspace: "workspaces"  # Directory for temporary agent workspaces

ui:
  display_type: "simple"
  logging_enabled: true
